[project]
name = "algorithm"
version = "0.1.0"
description = "Algorithm practice"
authors = [
    {name = "Jitae Choi"}
]
readme = "README.md"
requires-python = "3.10.17"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
