-- 코드를 입력하세요
SELECT DISTINCT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B
WHERE A.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                          FROM ANIMAL_OUTS)
ORDER BY A.DATETIME
LIMIT 3